name: materialx_flutter
description: Material X Flutter

version: 2.3.0+230

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  package_info: ^2.0.2
  http: ^0.13.4
  flutter_speed_dial: ^6.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.3
  flutter_local_notifications: ^9.6.1
  url_launcher: ^6.0.8
  device_info: ^2.0.2
  backdrop: ^0.8.0
  flutter_staggered_grid_view: ^0.4.1
  sqflite: ^2.0.2+1
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

